### ISSUE TITLE
Practical results

### ISSUE THREAD

**Issue by Ilyaprok** [bcbarbara/crazyflie_nmpc#1]
Hello, thank you very much for sharing this project. I am interested in NMPC and appliaction of this in quadrotors. Do you have any videos or any other results of this NMPC in Craziflie? Maybe any comparasion videos? Thank you:)

**Comment by bcbarbara** [comment]
Hi @Ilyaprok,
thanks for the interest in the project :) There's a video (not official yet) for the corresponding work here: https://youtu.be/nj1IJ_7Yisc. I hope to be able to update the repo as soon as possible with more official outcomes. So, I'm gonna leave this issue open until I really do it.

**Comment by bcbarbara** [comment]
An official video is now available at: https://youtu.be/xZLVQ7BdUHA.
