### ISSUE TITLE
Package Build Error 

### ISSUE THREAD

**Issue by RoboMichi** [bcbarbara/crazyflie_nmpc#3]
Hi @bcbarbara, 
I'm experiencing a build error when following the [steps provided](https://github.com/bcbarbara/crazyflie_nmpc/wiki/Install-on-Ubuntu-16.04-LTS-with-ROS-Kinetic) to install & compile the crazyflie NMPC workspace on a Oracle VM running Ubuntu-16.04-LTS. To me it seems like there's a library linkage problem between acados and blasfeo. When running the final installation step `catkin build`, the following error gets displayed: 

`[build] Found '7' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Starting  >>> crazyflie_cpp                                                    
Starting  >>> crazyflie_demo                                                   
Starting  >>> crazyflie_description                                            
Finished  <<< crazyflie_demo                       [ 0.2 seconds ]             
Starting  >>> crazyflie_controller                                             
Finished  <<< crazyflie_cpp                        [ 0.2 seconds ]             
Starting  >>> crazyflie_driver                                                 
Finished  <<< crazyflie_description                [ 0.1 seconds ]             
Starting  >>> crazyflie_tools                                                  
Finished  <<< crazyflie_tools                      [ 0.6 seconds ]             

Errors     << crazyflie_controller:make /home/hershal/catkin_ws/logs/crazyflie_controller/build.make.009.log
/usr/bin/ld: /home/hershal/catkin_ws/src/crazyflie_nmpc/crazyflie_controller/../acados/lib/libacados.a(ocp_nlp_cost_ls.o): undefined reference to symbol 'blasfeo_dsymv_l'
/opt/blasfeo/lib/libblasfeo.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hershal/catkin_ws/devel/.private/crazyflie_controller/lib/crazyflie_controller/acados_estimator] Error 1
make[1]: *** [CMakeFiles/acados_estimator.dir/all] Error 2
make: *** [all] Error 2
cd /home/hershal/catkin_ws/build/crazyflie_controller; catkin build --get-env crazyflie_controller | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << crazyflie_controller:make            [ Exited with code 2 ]      
Failed    <<< crazyflie_controller                 [ 1.4 seconds ]             
Finished  <<< crazyflie_driver                     [ 1.4 seconds ]             
[build] Summary: 5 of 6 packages succeeded.                                    
[build]   Ignored:   1 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 1.9 seconds total.`

I've consulted the installation pages for [acados](https://docs.acados.org/interfaces/) as well as [blasfeo](https://docs.acados.org/interfaces/index.html), reinstalled both packages and added the library paths to `LD_LIBRARY_PATH` respectively, but the error keeps showing up. Any idea why that keeps happening? Thanks

**Comment by bcbarbara** [comment]
Hi @RoboMichi,

were you able to build and install acados properly? (step 6 [here](https://github.com/bcbarbara/crazyflie_nmpc/wiki/Install-on-Ubuntu-16.04-LTS-with-ROS-Kinetic)). 
Besides, it seems that the package is searching for libblasfeo on ``/opt``, which is the wrong path. It should be searching in ``<acados_root>/lib`` instead. 
Are you sure your ``ACADOS_SOURCE_DIR=<acados_root>`` is correct?

**Comment by RoboMichi** [comment]
Hi @bcbarbara, 

sry for the late reply. You were right, `/opt` was the wrong path. That was an accidental leftover resulting from modifications I did to resolve the occurring issue. Though, this mistake did not alter the outcome. For verification I reran the installation steps you provided, leading to the following output: 

> Errors     << crazyflie_controller:make /home/hershal/catkin_ws/logs/crazyflie_controller/build.make.002.log
> /usr/bin/ld: /home/hershal/catkin_ws/src/crazyflie_nmpc/crazyflie_controller/../acados/lib/libacados.a(ocp_nlp_cost_ls.o): undefined reference to symbol 'blasfeo_dsymv_l'
> /home/hershal/catkin_ws/src/crazyflie_nmpc/acados/lib/libblasfeo.so: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [/home/hershal/catkin_ws/devel/.private/crazyflie_controller/lib/crazyflie_controller/acados_estimator] Error 1
> make[1]: *** [CMakeFiles/acados_estimator.dir/all] Error 2
> make: *** [all] Error 2
> cd /home/hershal/catkin_ws/build/crazyflie_controller; catkin build --get-env crazyflie_controller | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
> ...............................................................................
> Failed     << crazyflie_controller:make            [ Exited with code 2 ]      
> Failed    <<< crazyflie_controller                 [ 1.5 seconds ]             
> Finished  <<< crazyflie_driver                     [ 2.1 seconds ]             
> [build] Summary: 5 of 6 packages succeeded.                                    
> [build]   Ignored:   1 packages were skipped or are blacklisted.               
> [build]   Warnings:  None.                                                     
> [build]   Abandoned: None.                                                     
> [build]   Failed:    1 packages failed.                                        
> [build] Runtime: 2.7 seconds total. 

Yes I was able to build and install `acados` successfully via step 6, though I had to alter the command line input in step 6 to `$ make shared_library` following the `$ make -j4` as an error was thrown in step 11 telling me that the 'shared_lib' could not be found. `$ make shared_library` resolved that error and I could successfully continue to step 12.

**Comment by bcbarbara** [comment]
Hi @RoboMichi, 

could you try to change the library extension on [this line](https://github.com/bcbarbara/crazyflie_nmpc/blob/ca4ce33e7c4af88fcbf928bf71b80984a715bc73/crazyflie_controller/CMakeLists.txt#L71) and on [this line](https://github.com/bcbarbara/crazyflie_nmpc/blob/ca4ce33e7c4af88fcbf928bf71b80984a715bc73/crazyflie_controller/CMakeLists.txt#L81) from ``libacados.a`` -> ``libacados.so`` and run the installation again?

**Comment by RoboMichi** [comment]
Hi @bcbarbara , 

yes I've implemented your suggestions and its working, the build was successful. Thanks for your quick response and your support!

**Comment by bcbarbara** [comment]
Hi @RoboMichi,

thanks for reporting. I will fix that in the master branch.
